# Generated by Django 3.0.1 on 2020-01-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200115_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_times',
            field=models.IntegerField(default=0),
        ),
    ]
