# Generated by Django 3.0.2 on 2020-01-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='registered_date',
            new_name='mod_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='uName',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customersource',
            field=models.CharField(blank=True, max_length=50, verbose_name='CustomerSource'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pay',
            field=models.CharField(blank=True, max_length=50, verbose_name='is not pay'),
        ),
    ]
